<html>

<head>
    <style type="text/css">
        body {
            margin: 0;
        }
        
        #screen-liferay {
            width: 100%;
            height: 100%;
            background-image: url("media/liferay-home.png");
            background-size: 100%;
        }
    </style>
</head>

<body>
    <h2 style="float: left; margin-top: 130px;width: 100%;text-align: center;font-size:25px;color:grey">DEBUG - Liferay DXP running on : WEBSERVER</h2>
    <div id="screen-liferay"></div>
    
</body>

</html>

