<html>

<head>
    <style type="text/css">
        body {
            margin: 0;
        }
        
        #screen-liferay {
            width: 100%;
            height: 100%;
            background-image: url("media/liferay-home.png");
            background-size: 100%;
        }
    </style>
</head>

<body>
    <h2 style="font-size:200%;text-align:center;color:grey;">DEBUG - Liferay DXP running on : WEBSERVER</h2>
    <div id="screen-liferay"></div>
    <video widtd="1024" height="768" controls autoplay id="vid">
        <source src="media/rick.mp4" type="video/mp4">
    </video>
    <script>
        document.getElementById('vid').play();
    </script>

</body>

</html>

