apiVersion: apps/v1 
kind: Deployment
metadata:
   name: demo-page
   namespace: default
spec:
    selector:
        matchLabels:
            app: demo-page
    replicas: 1
    template:
        metadata:
            labels:
                app: demo-page
        spec:
            containers:
            - name: demopage
              image:  192.168.118.128:30002/devcondemo:v1
              imagePullPolicy: "Always"
              ports:
              - containerPort: 3000
