apiVersion: v1
kind: Service
metadata:
  name: "demo-page"
spec:
  selector:
    app: "demo-page"
  ports:
    - name: "demo-page"
      protocol: "TCP"
      port: 80
      targetPort: "webpage"
      nodePort: 30303
  type: NodePort
