apiVersion: apps/v1 
kind: Deployment
metadata:
   name: registry
   namespace: default
spec:
    selector:
        matchLabels:
            app: registry
    replicas: 1
    template:
        metadata:
            labels:
                app: registry
        spec:
            containers:
            - name: registry
              image:  registry:2
              ports:
              - containerPort: 5000


