apiVersion: v1
kind: Service
metadata:
  name: "registry"
spec:
  selector:
    app: "registry"
  ports:
    - name: "registry"
      protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 30002
  type: NodePort
