---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    app.kubernetes.io/component: ambassador-service
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
   - port: 80
  selector:
    service: ambassador
